### ISSUE TITLE
como debo preparar una imagen de una API propia para poder tratarla con `gatsby-image`?

### ISSUE THREAD

**Issue by horacioh** [horacioh/ama#2]
Una pregunta... estoy creando un sitio gatsby con api propia, como debería preparar la imagen para poder tratarla con gatsby sharp etc... en graphiql, me parece como un string 🤷‍♂️. mil gracias!

source: https://twitter.com/enmaska/status/1213995669872160768

**Comment by horacioh** [comment]
la API es GraphQL? si es GraphQL, podrias agregar la api al schema de Gatsby y poder crear un `fileNode` con `createRemoteFileNode`: https://gatsbyjs.org/packages/gatsby-source-filesystem/#createremotefilenode

creo que la API no necesita ser GraphQL, pero yo lo he hecho con una API GraphQL asi que no te puedo decir 100%!

**Comment by elgatoflaco** [comment]
Solucionado!!

La API es php, es de un proyecto antiguo 😅, he usado [gatsby-source-apiserver](https://www.gatsbyjs.org/packages/gatsby-source-apiserver/) para convertirla en GraphQL.

Luego desde gatsby-nody.js con `onCreateNode` recorro todos los nodos.

Luego recorro el array de imágenes y las descargo con `createRemoteFileNode`

Por último con `createNodeField` creo un nuevo campo y le asigno el valor creado por  `createRemoteFileNode`


```
exports.onCreateNode = async ({
  node,
  actions: { createNode, createNodeField },
  store,
  cache,
  createNodeId,
}) => {
  if (node.internal.type === "apiInmuebles") {
    if (node.images && !isEmpty(node.images)) {
      var images = await Promise.all(
        node.images.map(async image => {
          let fileNode

          try {
            fileNode = await createRemoteFileNode({
              url: image.url,
              parentNodeId: node.id, // id of the parent node of the fileNode you are going to create
              createNode, // helper function in gatsby-node to generate the node
              createNodeId, // helper function in gatsby-node to generate the node id
              cache, // Gatsby's cache
              store, // Gatsby's redux store
            })
          } catch (e) {
            console.log("e", e)
          }
          if (fileNode) {
            console.log("createdFile node")
            image.localFile___NODE = fileNode.id
            return image
          }
        })
      )

      await createNodeField({
        node,
        name: "images",
        value: images,
      })
    }
  }
}

```

Mil gracias por tu ayuda!!!

**Comment by horacioh** [comment]
me alegro que ya funcione!

**Comment by horacioh** [comment]
prueba de comment desde OneGraph
